FROM golang:1.16.2 as builder

RUN mkdir -p /var/log/app

ENV SRC_DIR=$GOPATH/src/app
RUN mkdir -p $SRC_DIR
WORKDIR $SRC_DIR
ADD ./app .

RUN go mod tidy

ARG CGO_ENABLED=0
ARG GOOS=linux
ARG GOARCH=amd64

RUN go build -ldflags="-w -s" -o /go/bin/app

FROM scratch
COPY --from=builder /go/bin/app /go/bin/app
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

EXPOSE 8080

ENTRYPOINT ["/go/bin/app"]