// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testFoods(t *testing.T) {
	t.Parallel()

	query := Foods()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testFoodsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Food{}
	if err = randomize.Struct(seed, o, foodDBTypes, true, foodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Foods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFoodsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Food{}
	if err = randomize.Struct(seed, o, foodDBTypes, true, foodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Foods().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Foods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFoodsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Food{}
	if err = randomize.Struct(seed, o, foodDBTypes, true, foodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FoodSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Foods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFoodsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Food{}
	if err = randomize.Struct(seed, o, foodDBTypes, true, foodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := FoodExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Food exists: %s", err)
	}
	if !e {
		t.Errorf("Expected FoodExists to return true, but got false.")
	}
}

func testFoodsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Food{}
	if err = randomize.Struct(seed, o, foodDBTypes, true, foodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	foodFound, err := FindFood(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if foodFound == nil {
		t.Error("want a record, got nil")
	}
}

func testFoodsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Food{}
	if err = randomize.Struct(seed, o, foodDBTypes, true, foodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Foods().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testFoodsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Food{}
	if err = randomize.Struct(seed, o, foodDBTypes, true, foodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Foods().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testFoodsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	foodOne := &Food{}
	foodTwo := &Food{}
	if err = randomize.Struct(seed, foodOne, foodDBTypes, false, foodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}
	if err = randomize.Struct(seed, foodTwo, foodDBTypes, false, foodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = foodOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = foodTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Foods().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testFoodsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	foodOne := &Food{}
	foodTwo := &Food{}
	if err = randomize.Struct(seed, foodOne, foodDBTypes, false, foodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}
	if err = randomize.Struct(seed, foodTwo, foodDBTypes, false, foodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = foodOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = foodTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Foods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func foodBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Food) error {
	*o = Food{}
	return nil
}

func foodAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Food) error {
	*o = Food{}
	return nil
}

func foodAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Food) error {
	*o = Food{}
	return nil
}

func foodBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Food) error {
	*o = Food{}
	return nil
}

func foodAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Food) error {
	*o = Food{}
	return nil
}

func foodBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Food) error {
	*o = Food{}
	return nil
}

func foodAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Food) error {
	*o = Food{}
	return nil
}

func foodBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Food) error {
	*o = Food{}
	return nil
}

func foodAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Food) error {
	*o = Food{}
	return nil
}

func testFoodsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Food{}
	o := &Food{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, foodDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Food object: %s", err)
	}

	AddFoodHook(boil.BeforeInsertHook, foodBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	foodBeforeInsertHooks = []FoodHook{}

	AddFoodHook(boil.AfterInsertHook, foodAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	foodAfterInsertHooks = []FoodHook{}

	AddFoodHook(boil.AfterSelectHook, foodAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	foodAfterSelectHooks = []FoodHook{}

	AddFoodHook(boil.BeforeUpdateHook, foodBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	foodBeforeUpdateHooks = []FoodHook{}

	AddFoodHook(boil.AfterUpdateHook, foodAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	foodAfterUpdateHooks = []FoodHook{}

	AddFoodHook(boil.BeforeDeleteHook, foodBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	foodBeforeDeleteHooks = []FoodHook{}

	AddFoodHook(boil.AfterDeleteHook, foodAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	foodAfterDeleteHooks = []FoodHook{}

	AddFoodHook(boil.BeforeUpsertHook, foodBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	foodBeforeUpsertHooks = []FoodHook{}

	AddFoodHook(boil.AfterUpsertHook, foodAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	foodAfterUpsertHooks = []FoodHook{}
}

func testFoodsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Food{}
	if err = randomize.Struct(seed, o, foodDBTypes, true, foodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Foods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFoodsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Food{}
	if err = randomize.Struct(seed, o, foodDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(foodColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Foods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFoodsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Food{}
	if err = randomize.Struct(seed, o, foodDBTypes, true, foodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFoodsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Food{}
	if err = randomize.Struct(seed, o, foodDBTypes, true, foodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FoodSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFoodsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Food{}
	if err = randomize.Struct(seed, o, foodDBTypes, true, foodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Foods().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	foodDBTypes = map[string]string{`ID`: `bigint`, `Name`: `varchar`, `Price`: `int`, `Note`: `varchar`}
	_           = bytes.MinRead
)

func testFoodsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(foodPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(foodAllColumns) == len(foodPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Food{}
	if err = randomize.Struct(seed, o, foodDBTypes, true, foodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Foods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, foodDBTypes, true, foodPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testFoodsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(foodAllColumns) == len(foodPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Food{}
	if err = randomize.Struct(seed, o, foodDBTypes, true, foodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Foods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, foodDBTypes, true, foodPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(foodAllColumns, foodPrimaryKeyColumns) {
		fields = foodAllColumns
	} else {
		fields = strmangle.SetComplement(
			foodAllColumns,
			foodPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := FoodSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testFoodsUpsert(t *testing.T) {
	t.Parallel()

	if len(foodAllColumns) == len(foodPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLFoodUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Food{}
	if err = randomize.Struct(seed, &o, foodDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Food: %s", err)
	}

	count, err := Foods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, foodDBTypes, false, foodPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Food struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Food: %s", err)
	}

	count, err = Foods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
